server:
  port: 8085

spring:
  application:
    name: currencyRateProvider
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_rate_provider
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/currency_rate_provider
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org.springframework.web: INFO